FROM cgr.dev/andrewd.dev/node:24-dev AS builder

WORKDIR /app

COPY package.json ./

RUN npm install --omit=dev

COPY index.js ./

# No Package Manager, No Shell or other utilities for maximum runtime security
FROM cgr.dev/andrewd.dev/node:24-slim

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/index.js ./index.js
COPY --from=builder /app/package*.json ./

EXPOSE 3000

ENTRYPOINT ["node", "index.js"]
